config {
 type: "view",
 schema: "dataform_demo",
 tags: ["reporting"],
 description: "get just the max runs for each home team"
 }

WITH runs_scored AS
                (
                    SELECT homeTeamName, MAX(homeFinalRuns) max_runs
                    FROM ${ref("games_wide")}
                    GROUP BY homeTeamName
                )
SELECT homeTeamName, max_runs
FROM runs_scored
ORDER BY homeTeamName


